all:
	python -m markdown rethink.md > rethink.html
	python -m markdown uber.md > uber.html
	python -m markdown alexa.md > alexa.html
	python -m markdown clearpath.md > clearpath.html
	python -m markdown fetch.md > fetch.html
	python -m markdown anki.md > anki.html
